### PR TITLE
double sl fit, and chi2 correlated Th implemented

### PR DESCRIPTION
**Pull request by camilocarrillo**
validate with 10k events http://wwwae.ciemat.es/~carrillo/dt/f04e520f0cda734903ba3e3d1373fe28afee5669/

### CODE REVIEW

**Comment by BrieucF** [comment]
Hi Camilo, 

Is it expected to have the BX of DT TP now ~400?
Screen Shot 2019-05-24 at 12 33 26 PM

**Comment by camilocarrillo** [comment]
Hi Brieuc,
please try with the development/master branch in principle the 400 should
be corrected back:
https://github.com/dtp2-tpg-am/cmssw/blob/AM_106X_dev/L1Trigger/DTPhase2Trigger/src/DTTrigPhase2Prod.cc#L326
Camilo

**Comment by BrieucF** [comment]
I am using the last dev/branch 'AM_106X_dev' and have the commit 'adding 400 shift back' in the git log (and did not forget to re-compile). Could you confirm that with this version of the code you see correct BX and t0?

**Comment by camilocarrillo** [comment]
We have changed the request for the MC correction with the run number instead of the event number just few hours ago! may be you are right and we had in this branch the wrong implementation! Let us know if you still see it after the last merge or here: https://github.com/cms-l1t-offline/cmssw/pull/771

**Comment by BrieucF** [comment]
Even using last version (including commit 'Changed BXId to Run number') DT bx is still ~ -400...

**Pull request merged**
